sudo: false
git:
  depth: 1
branches:
  only:
  - master
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install flake8
  - pip install pep257
# command to run tests
script:
  - flake8 . --max-line-length=160
  - pep257
notifications:
  email: false